src/Web/Controllers/BasketController.cs
using ApplicationCore.Entities;
using ApplicationCore.Interfaces;
using Infrastructure.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text.Json;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.ViewModels;

namespace Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketViewModelService _basketViewModelService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;

        public BasketController(IBasketViewModelService basketViewModelService, SignInManager<ApplicationUser> signInManager, IBasketService basketService,IOrderService orderService)
        {
            _basketViewModelService = basketViewModelService;
            _signInManager = signInManager;
            _basketService = basketService;
            this._orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = GetOrCreateUserId();
            return View(await _basketViewModelService.GetBasket(userId));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToBasket(int id, int quantity = 1)
        {
            // get product details
            var product = await _basketViewModelService.GetProductDetails(id);

            // get/create user id
            string userId = GetOrCreateUserId();

            // create basket if not exists and get basket id
            int basketId;
            if (!await _basketService.BasketExistsAsync(userId))
                basketId = await _basketService.CreateBasketAsync(userId);
            else
                basketId = await _basketService.GetBasketIdAsync(userId);

            // add item to the basket
            int count = await _basketService.AddItemToBasketAsync(basketId, product.Id, product.Price, quantity);

            return Json(new { BasketItemCount = count });
        }

        [HttpPost]
        public async Task<IActionResult> UpdateQuantity(int productId, int quantity)
        {
            var userId = GetOrCreateUserId();

            return Json(await _basketViewModelService.UpdateQuantity(userId, productId, quantity));
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            var vm = await CreateCheckoutViewModel();
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Checkout(CheckoutViewModel vm)
        {
            var newVm = await CreateCheckoutViewModel();
            if (vm.BasketItemsJson != newVm.BasketItemsJson)
            {
                ModelState.AddModelError("BasketItemsJson", "Your basket has been updated.Please review the items before making a payment.");
                ModelState.Remove("BasketItemJson"); // renew its valur and get it from newVm 
            }
            if (ModelState.IsValid)
            {
                //receive the payment

                //process the order
                var address = new Address()
                {
                    City = vm.City,
                    Country = vm.Country,
                    State = vm.State,
                    Street = vm.Street,
                    ZipCode = vm.ZipCode
                };
                int orderId=await _orderService.CreateOrderAsync(newVm.BasketId, vm.FirstName, vm.LastName,address);

                //delete the basket
                await _basketService.DeleteBasketAsync(newVm.BasketId);
                //redirect to success page
                return RedirectToAction("Success",new {orderId = orderId });
            }
            vm.BasketItems = newVm.BasketItems;
            vm.PaymentTotal = newVm.PaymentTotal;
            vm.BasketItemsJson = newVm.BasketItemsJson;
            return View(vm);
        }

        public async Task<IActionResult> Success(int orderId)
        {
            ViewBag.OrderId = orderId;
            return View();
        }

        private async Task<CheckoutViewModel> CreateCheckoutViewModel()
        {
            string userId = GetOrCreateUserId();
            var basket = await _basketViewModelService.GetBasket(userId);
            return new CheckoutViewModel() { BasketId=basket.Id,BasketItems = basket.Items, PaymentTotal = basket.Total(), BasketItemsJson = JsonSerializer.Serialize(basket.Items) };

        }
        private string GetOrCreateUserId()
        {
            if (_signInManager.IsSignedIn(User))
            {
                return User.FindFirst(ClaimTypes.NameIdentifier).Value;
            }
            else
            {
                if (Request.Cookies[Constants.BASKET_COOKIENAME] != null)
                {
                    return Request.Cookies[Constants.BASKET_COOKIENAME];
                }
                else
                {
                    var guid = Guid.NewGuid().ToString();
                    var cookieOptions = new CookieOptions();
                    cookieOptions.Expires = DateTime.Now.AddYears(1);
                    Response.Cookies.Append(Constants.BASKET_COOKIENAME, guid, cookieOptions);
                    return guid;
                }
            }
        }
    }
}

src/Web/ViewComponents/BasketItemCountViewComponent.cs
using ApplicationCore.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;

namespace Web.ViewComponents
{
    public class BasketItemCountViewComponent : ViewComponent
    {
        private readonly IBasketService _basketService;

        public BasketItemCountViewComponent(IBasketService basketService)
        {
            _basketService = basketService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // get logged in user id
            string userId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            // if not logged in, get anonymous user id from cookies
            if (userId == null)
                userId = Request.Cookies[Constants.BASKET_COOKIENAME];

            // if user id not exists, return 0 (it means there is no basket)
            if (userId == null)
                return Content("0");

            // if userId exists, get basket items count
            int count = await _basketService.BasketItemsCount(userId);
            return Content(count.ToString());
        }
    }
}

src/Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ped Food Company</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/toastr.js/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Basket" asp-action="Index">
                                Basket
                                <span class="badge badge-secondary" data-basket-item-count>
                                    @await Component.InvokeAsync("BasketItemCount")
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/Web/Views/Shared/_Pagination.cshtml
@model PaginationInfoViewModel

@{ 
    var prevData = Context.Request.Query.ToDictionary(x => x.Key, x => x.Value.ToString());
    if (!prevData.ContainsKey("pageId"))
        prevData.Add("pageId", null);
    prevData["pageId"] = (Model.CurrentPage - 1).ToString();
    var nextData = Context.Request.Query.ToDictionary(x => x.Key, x => x.Value.ToString());
    if (!nextData.ContainsKey("pageId"))
        nextData.Add("pageId", null);
    nextData["pageId"] = (Model.CurrentPage + 1).ToString();
}

<div class="row align-items-baseline">
    <div class="col-2">
        <a asp-all-route-data="prevData" class="btn btn-warning @(Model.HasPrevious ? "" : "disabled")">
            <i class="fas fa-arrow-left"></i>
        </a>
    </div>
    <div class="col-8 text-center">
        Showing @Model.ItemsOnPage of @Model.TotalItems products (Page @Model.CurrentPage/@Model.TotalPages)
    </div>
    <div class="col-2 text-right">
        <a asp-all-route-data="nextData" class="btn btn-warning @(Model.HasNext ? "" : "disabled")">
            <i class="fas fa-arrow-right"></i>
        </a>
    </div>
</div>